# action.yml
name: "GitHub Action for WeChat Work"
description: "Send WeChat Work message. Run on any operating platform, such as Windows, Linux, Mac supported by GitHub"
author: "billgo <hi@billgo.me>"
branding:
  icon: "message-circle"
  color: "blue"

inputs:
  webhook:
    description: "机器人的webhook地址"
    required: true
  msgtype:
    description: "当前支持格式: text, markdown"
    required: true
  content:
    description: "当 msgtype=text 时：文本内容，最长不超过 2048 个字节，必须是 utf8 编码；当 msgtype=text 时：markdown 内容，最长不超过 4096 个字节，必须是 utf8 编码 支持的格式详见 https://work.weixin.qq.com/api/doc/90000/90136/91770"
    required: false
  mentioned_list:
    description: "userid 的列表，提醒群中的指定成员(@某个成员)，@all表示提醒所有人，如果开发者获取不到 userid，可以使用 mentioned_mobile_list，必须是序列化后的 JSON 字符串"
    required: false
  mentioned_mobile_list:
    description: "手机号列表，提醒手机号对应的群成员(@某个成员)，@all表示提醒所有人，必须是序列化后的 JSON 字符串"
    required: false

runs:
  using: "node16"
  main: "lib/index.js"
